# External gems
gems:
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-paginate

exclude:
  - "/vendor/"

# Site settings
title: Fen0l
subtitle: "Discovering, Tips & Tricks and HowTo"
email: hello@anthonypradal.com
name: Anthony Pradal
description: >
  My blog. Do you live it ?

# root of your server.
baseurl: ""
url: "https://fen0l.github.io"
cover: "/assets/banner/header_image.jpg"
logo: "/assets/logo.png"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: false
highlightjs_theme: "monokai_sublime"

# Archive settings (see https://github.com/jekyll/jekyll-archives/)
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: 'archive'
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'

# Disqus comments
disqus_shortname: fenolsblog

# Google analytics
# ga_tracking_id: "UA-XXXX-1"

# Category descriptions (for archive pages)
descriptions:
  - cat: Info
    desc: "Posts describing me and this awesome blog."

  - cat: Synology
    desc: "This category reffer to Synology Systems."

social:
  - name: Twitter
    icon: twitter
    username: JokerSql
    url: https://twitter.com/JokerSql
    desc: Follow me on Twitter
    share: true

  - name: Facebook
    icon: facebook
    username: panthonyyyx
    url: https://facebook.com/panthonyyyx
    desc: Friend me on Facebook
    share: true

  - name: GitHub
    icon: github
    username: Fen0l
    url: https://github.com/Fen0l
    desc: Fork me on GitHub
    share: false

  - name: LinkedIn
    icon: linkedin
    username: Anthony Pradal
    url: https://www.linkedin.com/in/anthonypradal
    desc: Connect with me on LinkedIn
    share: true

# Social sharing protocols
# These are for automatically generating sharing metadata for FB and Twitter
# OS Protocol is for sharing the source of your site, if you're interested. For more, see osprotocol.com
protocols:
    fb_image: "/assets/logo.png"
    fb_image_width: 612
    fb_image_height: 605
    fb_image_type: "image/png"

    twitter_image: "/assets/logo.png"

    os_repo: "https://github.com/Fen0l/fen0l-blog"
    os_rcs_type: "git"
    os_src: "git@github.com:Fen0l/fen0l-blog.git"
